steps:
  - label: "API: Build, unit"
    command: ./docker_api_build.sh
    agents:
      stack: buildkite

  - label: "Test Consumer: build, test, Pact"
    command: ./docker_consumer_build.sh
    agents:
      stack: buildkite

  - wait

  - label: "API: Verify Pact"
    command: ./docker_api_verify.sh
    agents:
      stack: buildkite
